/**
 * Goal: to be able to randomly sample a string that can be generated from the
 * grammar.
 * 
 * 1. Find the total number of strings of a given size that can be produced
 * from the grammar
 * 2. Enumerate all the strings that can be produced from the grammar.
 * 3. Pick a specific string given its index in the enumeration.
 * 
 * Once we have the ability to do #2 and #3 we can then uniformly sample
 * from those indices.
 */

#include "../../fuzzer/src/c/grammar.h"
#include "hash_table.c"

/**
 * #1 : Counting the number of strings 
 *
 * We want to count the number of strings of a given size l_str which can be
 * generated by a token. Either:
 *      a) The token is a terminal. As a terminal will only produce itself,
 *          we just need to check if len(token) == l_str.
 *      b) The token is a non-terminal. Then the total number of strings of
 *          a given size which can be produced by the token is the total number
 *          of strings of a given size which can be produced by each of its
 *          decompositions.
 */
int key_get_num_strings(Token token, Grammar grammar, size_t l_str)
{
    if (!is_non_terminal(token))
    {
        // Do something
    }

    return 0;
}

int main()
{
    HashTable table;
    init_hash_table(&table);
    print_hash_table(&table);
}
